(()=>{"use strict";
const $=s=>document.querySelector(s);const viewport=$("#imageViewport");if(!viewport)return;let sourceCanvas=null,sourceReady=Promise.resolve(),dragMode=null,dragStart=null,titleRect=null,artistRect=null,dragging=false;const ignore=["プレイリスト","トラックタイトル","アーティスト","アルバム","ジャンル","bpm","評価","時間","レーティング","comment","comments","date","key","playlist","browser","rekordbox","recordbox"];
function setStatus(text,pct=0){const s=$("#ocrStatus"),p=$("#ocrPercent"),b=$("#ocrBar");if(s)s.textContent=text;if(p)p.textContent=pct?`${pct}%`:"";if(b)b.style.width=`${pct||0}%`}
function rememberFile(file){if(!file?.type?.startsWith("image/"))return;sourceReady=(async()=>{const bmp=await createImageBitmap(file),c=document.createElement("canvas");c.width=bmp.width;c.height=bmp.height;c.getContext("2d").drawImage(bmp,0,0);bmp.close();sourceCanvas=c;titleRect=artistRect=null})()}
$("#fileInput")?.addEventListener("change",e=>rememberFile(e.target.files?.[0]));viewport.addEventListener("drop",e=>rememberFile(e.dataTransfer?.files?.[0]),true);
function canvasPoint(e){const canvas=viewport.querySelector("canvas");if(!canvas)return null;const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(canvas.width,(e.clientX-r.left)*(canvas.width/r.width))),y:Math.max(0,Math.min(canvas.height,(e.clientY-r.top)*(canvas.height/r.height)))}}
function normRect(a,b){return{x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),w:Math.abs(a.x-b.x),h:Math.abs(a.y-b.y)}}
viewport.addEventListener("mousedown",e=>{if(e.target.tagName!=="CANVAS")return;dragMode=$("#selectArtistBtn")?.classList.contains("active")?"artist":"title";dragStart=canvasPoint(e);dragging=!!dragStart},true);window.addEventListener("mousemove",e=>{if(!dragging)return;const p=canvasPoint(e);if(!p)return;const r=normRect(dragStart,p);if(dragMode==="artist")artistRect=r;else titleRect=r},true);window.addEventListener("mouseup",e=>{if(!dragging)return;const p=canvasPoint(e);if(p){const r=normRect(dragStart,p);if(r.w>=8&&r.h>=8){if(dragMode==="artist")artistRect=r;else titleRect=r}}dragging=false},true);$("#clearCropBtn")?.addEventListener("click",()=>{titleRect=artistRect=null},true);
function cropCanvas(rect){const c=document.createElement("canvas"),x=Math.max(0,Math.round(rect.x)),y=Math.max(0,Math.round(rect.y)),w=Math.max(1,Math.round(rect.w)),h=Math.max(1,Math.round(rect.h));c.width=w;c.height=h;c.getContext("2d").drawImage(sourceCanvas,x,y,w,h,0,0,w,h);return c}
function otsu(hist,total){let sum=0;for(let i=0;i<256;i++)sum+=i*hist[i];let sumB=0,wB=0,max=0,thr=128;for(let t=0;t<256;t++){wB+=hist[t];if(!wB)continue;const wF=total-wB;if(!wF)break;sumB+=t*hist[t];const mB=sumB/wB,mF=(sum-sumB)/wF,v=wB*wF*(mB-mF)*(mB-mF);if(v>max){max=v;thr=t}}return thr}
function preprocess(rect,mode){const src=cropCanvas(rect),scale=Math.min(6,Math.max(3,2200/src.width)),c=document.createElement("canvas");c.width=Math.round(src.width*scale);c.height=Math.round(src.height*scale);const ctx=c.getContext("2d",{willReadFrequently:true});ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="high";ctx.drawImage(src,0,0,c.width,c.height);const img=ctx.getImageData(0,0,c.width,c.height),d=img.data,hist=new Array(256).fill(0),raw=new Uint8Array(c.width*c.height);let sum=0,k=0;for(let i=0;i<d.length;i+=4,k++){const g=Math.max(d[i],d[i+1],d[i+2]);raw[k]=g;hist[g]++;sum+=g}const total=raw.length,mean=sum/total;let acc=0,lo=0,hi=255;for(let i=0;i<256;i++){acc+=hist[i];if(acc>=total*.006){lo=i;break}}acc=0;for(let i=0;i<256;i++){acc+=hist[i];if(acc>=total*.994){hi=i;break}}const range=Math.max(18,hi-lo),mapped=new Uint8Array(total),hist2=new Array(256).fill(0);for(let i=0;i<total;i++){let v=((raw[i]-lo)/range)*255;v=(v-128)*1.5+128;v=Math.max(0,Math.min(255,v));if(mean<135)v=255-v;v=Math.round(v);mapped[i]=v;hist2[v]++}const threshold=otsu(hist2,total);for(let i=0,p=0;i<d.length;i+=4,p++){let v=mapped[p];if(mode==="threshold")v=v>threshold?255:0;d[i]=d[i+1]=d[i+2]=v;d[i+3]=255}ctx.putImageData(img,0,0);return c}
function cleanLines(text){return String(text||"").replace(/\r/g,"").split("\n").map(s=>s.replace(/[ \t]+/g," ").trim()).filter(line=>{if(!line)return false;if(!/[A-Za-z0-9ぁ-んァ-ヶ一-龯々〆ヵヶ]/.test(line))return false;const low=line.toLowerCase(),hits=ignore.reduce((n,w)=>n+(low.includes(w.toLowerCase())?1:0),0);if(hits>=2)return false;if(/^(アーティスト|アルバム|ジャンル|評価|時間|bpm|key|playlist|browser|rekordbox|recordbox)$/i.test(line))return false;return true})}
function norm(s){return s.normalize("NFKC").toLowerCase().replace(/\s+/g,"").replace(/[|｜]/g,"")}
function lev(a,b){a=norm(a);b=norm(b);const n=a.length,m=b.length;if(!n&&!m)return 0;if(!n)return m;if(!m)return n;let prev=Array.from({length:m+1},(_,i)=>i),cur=new Array(m+1);for(let i=1;i<=n;i++){cur[0]=i;for(let j=1;j<=m;j++)cur[j]=Math.min(cur[j-1]+1,prev[j]+1,prev[j-1]+(a[i-1]===b[j-1]?0:1));[prev,cur]=[cur,prev]}return prev[m]}
function sim(a,b){const M=Math.max(norm(a).length,norm(b).length);return M?1-lev(a,b)/M:1}function jpCount(s){return(s.match(/[ぁ-んァ-ヶ一-龯々〆ヵヶ]/g)||[]).length}function latinCount(s){return(s.match(/[A-Za-z]/g)||[]).length}
function align(ref,other){const n=ref.length,m=other.length,gap=-.65,dp=Array.from({length:n+1},()=>Array(m+1).fill(0)),bt=Array.from({length:n+1},()=>Array(m+1).fill(0));for(let i=1;i<=n;i++){dp[i][0]=i*gap;bt[i][0]=1}for(let j=1;j<=m;j++){dp[0][j]=j*gap;bt[0][j]=2}for(let i=1;i<=n;i++)for(let j=1;j<=m;j++){const pos=1-Math.abs((i-.5)/n-(j-.5)/m),match=.15+sim(ref[i-1],other[j-1])*1.6+pos*.65,a=dp[i-1][j-1]+match,b=dp[i-1][j]+gap,c=dp[i][j-1]+gap;if(a>=b&&a>=c){dp[i][j]=a;bt[i][j]=0}else if(b>=c){dp[i][j]=b;bt[i][j]=1}else{dp[i][j]=c;bt[i][j]=2}}const out=Array(n).fill(null);let i=n,j=m;while(i>0||j>0){const t=bt[i][j];if(i>0&&j>0&&t===0){out[i-1]=other[j-1];i--;j--}else if(i>0&&(j===0||t===1))i--;else j--}return out}
function choose(cands){cands=cands.filter(x=>x?.text);if(!cands.length)return"";if(cands.length===1)return cands[0].text;const groups=new Map;for(const c of cands){const k=norm(c.text);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(c)}const majority=[...groups.values()].sort((a,b)=>b.length-a.length)[0];if(majority.length>=2){const m=majority[0].text,mixed=cands.find(c=>c.src==="mix");if(!(mixed&&latinCount(mixed.text)>=4&&jpCount(m)>0&&sim(m,mixed.text)<.3))return m}const japanese=cands.filter(c=>jpCount(c.text)>0),latinOnly=cands.filter(c=>jpCount(c.text)===0&&latinCount(c.text)>0);if(japanese.length&&latinOnly.length&&cands.every(c=>norm(c.text).length<=2))return japanese.sort((a,b)=>jpCount(b.text)-jpCount(a.text))[0].text;let best=cands[0],bestScore=-1e9;for(const c of cands){let score=0,txt=c.text,jp=jpCount(txt),lat=latinCount(txt);for(const o of cands)if(o!==c)score+=sim(txt,o.text)*2.2;if(c.src.startsWith("ja"))score+=jp*.18;if(c.src==="mix"&&lat>=4&&jp===0)score+=1.4;if(/[�□■]/.test(txt))score-=3;if((txt.match(/[|_=~]/g)||[]).length>2)score-=2;const mix=cands.find(x=>x.src==="mix");if(mix&&jp>jpCount(mix.text)&&sim(txt,mix.text)>=.55)score+=1.8;if(mix&&jp>0&&latinCount(mix.text)>=4&&sim(txt,mix.text)<.25)score-=1.5;if(score>bestScore){bestScore=score;best=c}}return best.text}
function mergePasses(jaSoft,jaBw,mix){const sets=[{src:"jaSoft",lines:cleanLines(jaSoft)},{src:"jaBw",lines:cleanLines(jaBw)},{src:"mix",lines:cleanLines(mix)}],ref=sets.slice().sort((a,b)=>b.lines.length-a.lines.length)[0],aligned=sets.map(s=>s===ref?s.lines:align(ref.lines,s.lines));return ref.lines.map((_,i)=>choose(sets.map((s,k)=>({src:s.src,text:aligned[k][i]})))).filter(Boolean)}
async function createWorkers(){setStatus("高精度OCRエンジン準備中…",3);const ja=await Tesseract.createWorker("jpn",1),mix=await Tesseract.createWorker(["jpn","eng"],1);await ja.setParameters({preserve_interword_spaces:"1",tessedit_pageseg_mode:"6",user_defined_dpi:"300"});await mix.setParameters({preserve_interword_spaces:"1",tessedit_pageseg_mode:"6",user_defined_dpi:"300"});return{ja,mix}}
async function ocrColumn(rect,label,workers,base){const soft=preprocess(rect,"soft"),bw=preprocess(rect,"threshold");setStatus(`${label}: 日本語専用OCR 1/3`,base);const a=await workers.ja.recognize(soft);setStatus(`${label}: 日本語専用OCR 2/3`,base+12);const b=await workers.ja.recognize(bw);setStatus(`${label}: 日本語+英語OCR 3/3`,base+24);const c=await workers.mix.recognize(soft);return mergePasses(a.data.text,b.data.text,c.data.text)}
async function runEnhanced(e){e.preventDefault();e.stopImmediatePropagation();await sourceReady;if(!sourceCanvas||!titleRect||!artistRect){setStatus("曲名範囲とアーティスト範囲をもう一度選択してください",0);return}let workers;try{workers=await createWorkers();const titles=await ocrColumn(titleRect,"曲名",workers,8),artists=await ocrColumn(artistRect,"アーティスト",workers,52),count=Math.max(titles.length,artists.length);$("#rawText").value=Array.from({length:count},(_,i)=>`${titles[i]||""}\t${artists[i]||""}`).join("\n");$("#reparseBtn").click();setStatus(`高精度OCR完了：曲名 ${titles.length}行 / アーティスト ${artists.length}行`,100)}catch(err){setStatus(`高精度OCRエラー: ${err?.message||err}`,0)}finally{try{await workers?.ja?.terminate()}catch{}try{await workers?.mix?.terminate()}catch{}}}
$("#runDualBtn")?.addEventListener("click",runEnhanced,true);
})();