(()=>{"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
let tracks=loadJSON("vj-simple-tracks",[]),sourceCanvas=null,displayCanvas=null,displayCtx=null,dragging=false,dragStart=null,viewScale=1;
let titleRect=null,artistRect=null,activeCrop='title';
const ignoreDefault=["プレイリスト","トラックタイトル","アーティスト","アルバム","ジャンル","bpm","評価","時間","レーティング","comment","comments","date","key"];
function loadJSON(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}function saveTracks(){localStorage.setItem("vj-simple-tracks",JSON.stringify(tracks))}
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$(`#view-${b.dataset.tab}`).classList.add('active')});
const viewport=$('#imageViewport'),fileInput=$('#fileInput');
fileInput.onchange=async e=>{const f=e.target.files?.[0];if(f)await handleImage(f)};
viewport.ondragover=e=>e.preventDefault();viewport.ondrop=async e=>{e.preventDefault();const f=e.dataTransfer.files?.[0];if(f)await handleImage(f)};
$('#zoomOutBtn').onclick=()=>setZoom(viewScale-.25);$('#zoomInBtn').onclick=()=>setZoom(viewScale+.25);$('#zoom100Btn').onclick=()=>setZoom(1);$('#zoomFitBtn').onclick=fitImage;
viewport.addEventListener('wheel',e=>{if(!e.ctrlKey||!sourceCanvas)return;e.preventDefault();setZoom(viewScale+(e.deltaY<0?.25:-.25),e)},{passive:false});
$('#rerunFullBtn').onclick=()=>runFullOcr();$('#selectTitleBtn').onclick=()=>setCropMode('title');$('#selectArtistBtn').onclick=()=>setCropMode('artist');$('#runDualBtn').onclick=()=>runDualOcr();$('#clearCropBtn').onclick=clearCrops;$('#addBlankBtn').onclick=()=>addBlank();$('#reparseBtn').onclick=reparse;$('#applyIgnoreBtn').onclick=reparse;
async function handleImage(file){if(!file.type.startsWith('image/'))return setOcr('画像ファイルを選択してください',0);const bmp=await createImageBitmap(file);sourceCanvas=document.createElement('canvas');sourceCanvas.width=bmp.width;sourceCanvas.height=bmp.height;sourceCanvas.getContext('2d').drawImage(bmp,0,0);bmp.close();createDisplay();clearCrops();enableImageButtons(true);setCropMode('title');setOcr('曲名範囲→アーティスト範囲の順に選択してください',0)}
function createDisplay(){viewport.innerHTML='';displayCanvas=document.createElement('canvas');displayCanvas.width=sourceCanvas.width;displayCanvas.height=sourceCanvas.height;displayCanvas.style.cursor='crosshair';viewport.appendChild(displayCanvas);displayCtx=displayCanvas.getContext('2d');bindCrop();renderCanvas();requestAnimationFrame(fitImage)}
function clampZoom(v){return Math.max(.25,Math.min(4,Math.round(v*4)/4))}function setZoom(v,anchor=null){if(!displayCanvas)return;const old=viewScale,newS=clampZoom(v);let ix,iy;if(anchor){const r=viewport.getBoundingClientRect();ix=(anchor.clientX-r.left+viewport.scrollLeft)/old;iy=(anchor.clientY-r.top+viewport.scrollTop)/old}viewScale=newS;applyZoom();if(anchor){const r=viewport.getBoundingClientRect();viewport.scrollLeft=ix*newS-(anchor.clientX-r.left);viewport.scrollTop=iy*newS-(anchor.clientY-r.top)}}
function applyZoom(){if(!displayCanvas)return;displayCanvas.style.width=`${Math.round(sourceCanvas.width*viewScale)}px`;displayCanvas.style.height=`${Math.round(sourceCanvas.height*viewScale)}px`;$('#zoomValue').textContent=`${Math.round(viewScale*100)}%`;$('#zoomOutBtn').disabled=viewScale<=.25;$('#zoomInBtn').disabled=viewScale>=4}
function fitImage(){if(!sourceCanvas)return;viewScale=Math.max(.25,Math.min(1,(viewport.clientWidth-18)/sourceCanvas.width));applyZoom();viewport.scrollLeft=viewport.scrollTop=0}
function pointFromEvent(e){const r=displayCanvas.getBoundingClientRect();return{x:Math.max(0,Math.min(displayCanvas.width,(e.clientX-r.left)*(displayCanvas.width/r.width))),y:Math.max(0,Math.min(displayCanvas.height,(e.clientY-r.top)*(displayCanvas.height/r.height)))}}
function bindCrop(){displayCanvas.onmousedown=e=>{dragging=true;dragStart=pointFromEvent(e);setActiveRect({x:dragStart.x,y:dragStart.y,w:0,h:0});renderCanvas()};window.addEventListener('mousemove',e=>{if(!dragging||!displayCanvas)return;const c=pointFromEvent(e);setActiveRect(normRect({x:dragStart.x,y:dragStart.y,w:c.x-dragStart.x,h:c.y-dragStart.y}));renderCanvas()});window.addEventListener('mouseup',()=>{if(!dragging)return;dragging=false;const r=getActiveRect();if(r&&(r.w<12||r.h<12))setActiveRect(null);renderCanvas();syncCrop();if(activeCrop==='title'&&titleRect)setCropMode('artist')})}
function normRect(r){return{x:r.w<0?r.x+r.w:r.x,y:r.h<0?r.y+r.h:r.y,w:Math.abs(r.w),h:Math.abs(r.h)}}
function getActiveRect(){return activeCrop==='title'?titleRect:artistRect}function setActiveRect(r){if(activeCrop==='title')titleRect=r;else artistRect=r}
function setCropMode(mode){activeCrop=mode;$('#selectTitleBtn').classList.toggle('active',mode==='title');$('#selectArtistBtn').classList.toggle('active',mode==='artist');$('#cropModePill').textContent=mode==='title'?'選択中: 曲名列':'選択中: アーティスト列';renderCanvas()}
function drawCrop(rect,color,label,active){if(!rect)return;const x=Math.max(0,rect.x),y=Math.max(0,rect.y),right=Math.min(displayCanvas.width,rect.x+rect.w),bottom=Math.min(displayCanvas.height,rect.y+rect.h);displayCtx.save();displayCtx.strokeStyle=color;displayCtx.lineWidth=active?3:2;displayCtx.setLineDash(active?[10,5]:[6,5]);displayCtx.strokeRect(x,y,right-x,bottom-y);displayCtx.setLineDash([]);displayCtx.fillStyle=color+'12';displayCtx.fillRect(x,y,right-x,bottom-y);displayCtx.font='bold 12px sans-serif';const text=`${label} ${Math.round(right-x)}×${Math.round(bottom-y)}`,w=displayCtx.measureText(text).width+12;displayCtx.fillStyle='#071018e8';displayCtx.fillRect(x,Math.max(0,y-26),w,22);displayCtx.fillStyle=color;displayCtx.fillText(text,x+6,Math.max(15,y-11));displayCtx.restore()}
function renderCanvas(){if(!displayCtx||!sourceCanvas)return;displayCtx.clearRect(0,0,displayCanvas.width,displayCanvas.height);displayCtx.drawImage(sourceCanvas,0,0);drawCrop(titleRect,'#3dd7ff','曲名',activeCrop==='title');drawCrop(artistRect,'#56e39f','アーティスト',activeCrop==='artist')}
function clearCrops(){titleRect=null;artistRect=null;renderCanvas();syncCrop()}function syncCrop(){const title=!!titleRect,artist=!!artistRect;$('#runDualBtn').disabled=!(title&&artist);$('#clearCropBtn').disabled=!(title||artist);$('#titleCropPill').textContent=title?'曲名範囲: 設定済':'曲名範囲: 未設定';$('#artistCropPill').textContent=artist?'アーティスト範囲: 設定済':'アーティスト範囲: 未設定'}function enableImageButtons(on){['#rerunFullBtn','#selectTitleBtn','#selectArtistBtn','#zoomOutBtn','#zoomInBtn','#zoom100Btn','#zoomFitBtn'].forEach(id=>$(id).disabled=!on);syncCrop();if(on)applyZoom()}
function canvasBlob(c){return new Promise((ok,ng)=>c.toBlob(b=>b?ok(b):ng(new Error('画像変換失敗')),'image/png'))}async function rectBlob(rect){const c=document.createElement('canvas'),x=Math.round(rect.x),y=Math.round(rect.y),w=Math.max(1,Math.round(rect.w)),h=Math.max(1,Math.round(rect.h));c.width=w;c.height=h;c.getContext('2d').drawImage(sourceCanvas,x,y,w,h,0,0,w,h);return canvasBlob(c)}
async function preprocess(blob,mode){const bmp=await createImageBitmap(blob);const targetW=Math.min(3200,Math.max(1500,Math.min(bmp.width*4,3200))),scale=targetW/bmp.width,c=document.createElement('canvas');c.width=Math.round(bmp.width*scale);c.height=Math.round(bmp.height*scale);const ctx=c.getContext('2d',{willReadFrequently:true});ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(bmp,0,0,c.width,c.height);bmp.close();const img=ctx.getImageData(0,0,c.width,c.height),d=img.data,hist=new Array(256).fill(0);let graySum=0;for(let i=0;i<d.length;i+=4){const g=Math.round(d[i]*.2126+d[i+1]*.7152+d[i+2]*.0722);hist[g]++;graySum+=g}const total=c.width*c.height,mean=graySum/total;let acc=0,lo=0,hi=255;for(let i=0;i<256;i++){acc+=hist[i];if(acc>=total*.008){lo=i;break}}acc=0;for(let i=0;i<256;i++){acc+=hist[i];if(acc>=total*.992){hi=i;break}}const range=Math.max(22,hi-lo),invert=mean<120;for(let i=0;i<d.length;i+=4){const g=d[i]*.2126+d[i+1]*.7152+d[i+2]*.0722;let v=((g-lo)/range)*255;v=(v-128)*1.42+128;v=Math.max(0,Math.min(255,v));if(invert)v=255-v;if(mode==='threshold')v=v>148?255:0;d[i]=d[i+1]=d[i+2]=v;d[i+3]=255}ctx.putImageData(img,0,0);return canvasBlob(c)}
async function ocrBlob(blob,label,progressBase=0){const soft=await preprocess(blob,'soft');const worker=await Tesseract.createWorker(['jpn','eng'],1,{logger:m=>{if(typeof m.progress==='number')setOcr(`${label} OCR中…`,Math.min(94,progressBase+Math.round(m.progress*34)))}});await worker.setParameters({preserve_interword_spaces:'1',tessedit_pageseg_mode:'6',user_defined_dpi:'300'});const r1=await worker.recognize(soft);setOcr(`${label} 追加解析中…`,Math.min(95,progressBase+36));const bw=await preprocess(blob,'threshold'),r2=await worker.recognize(bw);await worker.terminate();const t1=sanitizeColumn(r1.data.text||''),t2=sanitizeColumn(r2.data.text||'');return scoreColumn(t2)>scoreColumn(t1)?t2:t1}
function ignoreWords(){return[...ignoreDefault,...($('#customIgnore').value||'').split(',').map(x=>x.trim()).filter(Boolean)]}function sanitizeColumn(text){const words=ignoreWords();return text.replace(/\r/g,'').split('\n').map(s=>s.replace(/[ \t]+/g,' ').trim()).filter(line=>{if(!line||line.length<=1)return false;const lower=line.toLowerCase(),hits=words.reduce((n,w)=>n+(lower.includes(w.toLowerCase())?1:0),0);if(hits>=2)return false;if(/^(アーティスト|アルバム|ジャンル|評価|時間|bpm|key|playlist|browser|rekordbox|recordbox)$/i.test(line))return false;if(/^[|\[\]()\-_=~:;,.!?\\/]+$/.test(line))return false;return true}).join('\n')}function scoreColumn(t){const lines=t.split(/\r?\n/).filter(Boolean),jp=(t.match(/[ぁ-んァ-ン一-龯々〆ヵヶ]/g)||[]).length,bad=(t.match(/[|_=]{2,}/g)||[]).length;return lines.length*12+jp*.35+t.length/80-bad*4}
async function runFullOcr(){if(!sourceCanvas)return;try{setOcr('画像全体を解析中…',2);const text=await ocrBlob(await canvasBlob(sourceCanvas),'全体',8);$('#rawText').value=text;reparse();setOcr(`全体OCR完了：${tracks.length}件`,100)}catch(e){setOcr(`OCRエラー: ${e?.message||e}`,0)}}
async function runDualOcr(){if(!titleRect||!artistRect)return;try{setOcr('曲名列を高精度解析中…',2);const titleText=await ocrBlob(await rectBlob(titleRect),'曲名',5);setOcr('アーティスト列を高精度解析中…',48);const artistText=await ocrBlob(await rectBlob(artistRect),'アーティスト',52);const titles=titleText.split('\n').map(cleanLine).filter(Boolean),artists=artistText.split('\n').map(cleanLine).filter(Boolean),count=Math.max(titles.length,artists.length);tracks=[];for(let i=0;i<count;i++)tracks.push({id:uid(),title:titles[i]||'',artist:artists[i]||'',ready:false});$('#rawText').value=Array.from({length:count},(_,i)=>`${titles[i]||''}\t${artists[i]||''}`).join('\n');saveTracks();renderTracks();setOcr(`2列OCR完了：曲名 ${titles.length}行 / アーティスト ${artists.length}行`,100)}catch(e){setOcr(`OCRエラー: ${e?.message||e}`,0)}}
function cleanLine(line){return line.replace(/^\s*(?:[#№]?\s*\d{1,3}\s*[.\-:：)\]】、]?\s*|[①-⑳]\s*)/,'').trim()}
function setOcr(t,p){$('#ocrStatus').textContent=t;$('#ocrPercent').textContent=p?`${p}%`:'';$('#ocrBar').style.width=`${p||0}%`}
function reparse(){const raw=$('#rawText').value.replace(/\r/g,'').split('\n').map(s=>s.trim()).filter(Boolean),out=[];for(const line of raw){if(line.includes('\t')){const [title,...rest]=line.split('\t');out.push({id:uid(),title:cleanLine(title),artist:rest.join(' ').trim(),ready:false});continue}if(shouldIgnore(line))continue;const v=cleanLine(line);if(v.length>1)out.push({id:uid(),title:v,artist:'',ready:false})}tracks=out;saveTracks();renderTracks()}function shouldIgnore(line){const lower=line.toLowerCase(),hits=ignoreWords().reduce((n,w)=>n+(lower.includes(w.toLowerCase())?1:0),0);return hits>=2||/^(アーティスト|アルバム|ジャンル|評価|時間|bpm|key|playlist|browser|collection|search)$/i.test(line)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function yt(t){return`https://www.youtube.com/results?search_query=${encodeURIComponent([t.artist,t.title,'official MV'].filter(Boolean).join(' '))}`}function addBlank(after=null){const t={id:uid(),title:'',artist:'',ready:false};if(!after)tracks.push(t);else{const i=tracks.findIndex(x=>x.id===after);i<0?tracks.push(t):tracks.splice(i+1,0,t)}saveTracks();renderTracks()}
function renderTracks(){const host=$('#tracks'),ready=tracks.filter(t=>t.ready).length;$('#readyBadge').textContent=`${ready}/${tracks.length} 準備済`;if(!tracks.length){host.innerHTML='<div class="empty"><div>曲名範囲とアーティスト範囲を選択して「2列OCR実行」を押してください。<br><br><button id="emptyAdd" class="btn secondary">＋ 手動で1曲追加</button></div></div>';$('#emptyAdd')?.addEventListener('click',()=>addBlank());return}host.innerHTML='';tracks.forEach((t,i)=>{const g=document.createElement('div');g.className='row-group';g.dataset.id=t.id;g.innerHTML=`<article class="track"><div class="num">${String(i+1).padStart(2,'0')}</div><div class="edit"><input class="title" placeholder="曲名" value="${esc(t.title)}"><input class="artist" placeholder="アーティスト" value="${esc(t.artist)}"></div><div class="actions"><a class="btn youtube yt" target="_blank">YouTube検索</a><label class="ready"><input class="readyBox" type="checkbox" ${t.ready?'checked':''}>準備済</label><button class="x">×</button></div></article><button class="insert">＋ この下に空白曲を追加</button>`;const ti=g.querySelector('.title'),ar=g.querySelector('.artist'),link=g.querySelector('.yt'),sync=()=>{t.title=ti.value;t.artist=ar.value;link.href=yt(t);saveTracks()};ti.oninput=ar.oninput=sync;sync();g.querySelector('.readyBox').onchange=e=>{t.ready=e.target.checked;saveTracks();renderTracks()};g.querySelector('.x').onclick=()=>{tracks=tracks.filter(x=>x.id!==t.id);saveTracks();renderTracks()};g.querySelector('.insert').onclick=()=>addBlank(t.id);host.appendChild(g)})}renderTracks();
})();
